baseURL = "https://edripley.com"
languageCode = "en-gb"
title = "Ed Ripley"
assetdir = "."
pluralizelisttitles = false
sectionPagesMenu = "main"
# googleAnalytics = "UA-142187310-1" TODO

[params]
subtitle = "Producer | Mixer | Composer"
fontConfig = "Open Sans"
dateformat = "Jan 2, 2006"

## Uncomment to enable the top banner.
# [params.banner]
# text = "Click this banner, woo!"
# link = "https://google.com"

[params.unpkg]
css = [
	"normalize.css/normalize.css"
]
js = [
	"imagesloaded@4/imagesloaded.pkgd.min.js",
	"masonry-layout@4/dist/masonry.pkgd.min.js"
]

[params.social]
instagram = "https://www.instagram.com/edripley"

[[params.nav]]
identifier = "Work"
url = "/work/"
weight = 1

[[params.nav]]
identifier = "Showreel"
url = "/showreel/"
weight = 2

[[params.nav]]
identifier = "About"
url = "/about/"
weight = 3

# Enable inline HTML in Markdown files (Hugo >0.64)
[markup.goldmark.renderer]
unsafe = true
